/* tslint:disable */
/* eslint-disable */
/**
 * Autify API
 * ## Authorization You can authenticate the API by using a personal access token and passing it to the Bearer header. To generate or manage API keys、please visit [your account page](https://app.autify.com/settings).  Example of using a personal access token in the header： ``` curl -H \"Authorization: Bearer YOUR_PERSONAL_ACCESS_TOKEN\" https://app.autify.com/api/v1/ ```  If the credentials are invalid or omitted, an error message is returned with status code 401： ``` {   \"errors\":[{     \"message\": \"Bad credentials\"   }] } ```  ## Overview Currently, we support the following APIs. For more details, open the toggle for each endpoint.  * Schedule: Request a test execution by specifying a test_plan ID. * Scenario: Get a list of scenarios. The detail of the scenario will be returned when a scenario ID is specified. * Result: Get a list of test results. The detail of the test result will be returned when a test result ID is specified. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

